FROM docker.io/mdiblbiocore/seurat:latest

RUN Rscript -e "install.packages(c('argparse', 'anndata'), repos='https://cloud.r-project.org')"
RUN Rscript -e "loupeR::setup()"


COPY scripts/create_loupe_file.R scripts/create_all_loupe_file.R scripts/log_utils.py /usr/local/bin/

# Make sure it’s executable
RUN chmod +x -R /usr/local/bin/*.py /usr/local/bin/*.R

WORKDIR /workspace

 #Set the default command
CMD ["/bin/bash"]