FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libhdf5-dev \
    libxml2-dev \
    libffi-dev \
    libssl-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    libwebp-dev \
    libopenblas-dev \
    liblapack-dev \
    zlib1g-dev \
    liblz4-dev \
    libzstd-dev \
    libbz2-dev \
    liblzma-dev \
    libsqlite3-dev \
    libncurses5-dev \
    pkg-config \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir \
    numpy==1.23.5 \
    matplotlib==3.6.3 \
    seaborn==0.12.2 \
    statsmodels==0.14.5 \
    patsy==1.0.2 \
    scipy==1.11.4 \
    scikit-learn==1.3.0 \
    pandas==1.5.3 \
    anndata==0.8.0 \
    scanpy==1.9.3 \
    h5py==3.8.0 \
    numba==0.56.3 \
    llvmlite==0.39.1 \
    umap-learn==0.5.3 \
    pynndescent==0.5.13 \
    leidenalg==0.10.2 \
    igraph==0.11.9 \
    harmonypy==0.0.10 \
    hnswlib==0.7.0 \
    fast-histogram==0.14 \
    sam-algorithm==1.0.2 \
    samap==1.0.15 \
    holoviews-samap==1.0.1 \
    bokeh==3.2.2 \
    panel==1.2.3 \
    param==1.13.0 \
    colorcet==3.1.0 \
    pyviz-comms==3.0.6 \
    networkx==3.4.2 \
    natsort==8.4.0 \
    joblib==1.5.2 \
    tqdm==4.67.1 \
    dill==0.4.0 \
    pyyaml==6.0.3 \
    requests==2.32.5 \
    jinja2==3.1.6 \
    markupsafe==3.0.3 \
    markdown==3.9 \
    markdown-it-py==4.0.0 \
    mdit-py-plugins==0.5.0 \
    mdurl==0.1.2 \
    linkify-it-py==2.0.3 \
    uc-micro-py==1.0.3 \
    bleach==6.2.0 \
    webencodings==0.5.1 \
    tornado==6.5.2 \
    xyzservices==2025.4.0 \
    session-info==1.0.1 \
    stdlib-list==0.12.0 \
    texttable==1.7.0 \
    logutils==0.3.5 \
    packaging==25.0 \
    charset-normalizer==3.4.4 \
    idna==3.11 \
    urllib3==2.5.0 \
    six==1.17.0 \
    python-dateutil==2.9.0.post0 \
    pytz==2025.2 \
    typing_extensions==4.15.0 \
    pyparsing==3.2.5 \
    cycler==0.12.1 \
    fonttools==4.60.1 \
    kiwisolver==1.4.9 \
    contourpy==1.3.2 \
    pillow==11.3.0 \
    threadpoolctl==3.6.0 

COPY scripts/summary_samap.py scripts/connected_de.py scripts/additional_analysis.py scripts/create_loupe_input.py scripts/log_utils.py /usr/local/bin/

# Make sure it’s executable
RUN chmod +x -R /usr/local/bin/*.py

WORKDIR /workspace

 #Set the default command
CMD ["/bin/bash"]