#!/usr/env/bin nextflow

/*
 *  PIPELINE: main.nf
 *
 *  Description:
 *      SAMap-based cross-species transcriptome mapping pipeline.
 *      Performs preprocessing of input metadata, reciprocal BLAST between
 *      species, SAMap alignment, and visualization of results.
 *
 *  Inputs:
 *      - data/transcriptomes/*.fasta      Input transcriptome FASTA files
 *      - data/*.h5ad                      Precomputed AnnData files
 *      - sample_sheet.csv                 Sample metadata sheet
 *
 *  Workflow Overview:
 *      1. Preprocess sample sheet to classify inputs and assign IDs
 *      2. Generate all unordered species pairs
 *      3. Run reciprocal BLAST on each species pair
 *      4. Build a SAMap object
 *      5. Run SAMap on each BLAST result
 *      6. Visualize SAMap alignment and write results
 *
 *  Parameters:
 *      --run_id        Run ID provided by user. If none is provided a timestamp is used. Default: null
 *      --sample_sheet  Path to the sample sheet provided by user. Default: 'sample_sheet.csv'
 *      --maps_dir      Path to a directory containing precomputed BLAST maps if any are provided. 
 *                      Any value other than null will skip the BLAST module. Default: null
 *      --outdir   The directory all where all results will be stored. Default: '.'
 *
 *  Outputs:
 *      - results_dir/run_id/sample_sheet.csv       Updated metadata with type and ID
 *      - results_dir/run_id/maps/                  Reciprocal BLAST outputs per sample pair
 *      - results_dir/run_id/samap_objects/         Pickled SAMap object (Python)
 *      - results_dir/run_id/plots/chord.html       Chord plot
 *      - results_dir/run_id/plots/sankey.html      Mapping Sankey diagram
 *      - results_dir/run_id/plots/scatter.png      Gene mapping scatter plot
 *      - results_dir/run_id/csv/hms.csv            Highest mapping scores (HMS) matrix
 *      - results_dir/run_id/csv/pms.csv            Pairwise mapping scores (PMS) matrix
 *      - results_dir/run_id/logs/*.log             Logfiles generated by the modules.
 *
 *  Author:     Markus Sujansky, Ryan Sonderman
 *  Created:    2025-06-12
 *  Last Modified: 2025-09-10
 *  Version:    1.1.1
 */

// Import the required modules 
include { PREPROCESS_SEURAT_OBJECT } from './modules/preprocess_seurat_object.nf'
include { PREPROCESS_ANNDATA_OBJECT } from './modules/preprocess_anndata_object.nf'
include { RUN_BLAST_PAIR } from './modules/run_blast_pair.nf'
include { LOAD_SAMS } from './modules/load_sams.nf'
include { BUILD_SAMAP } from './modules/build_samap.nf'
include { RUN_SAMAP } from './modules/run_samap.nf'
include { VISUALIZE_SAMAP } from './modules/visualize_samap.nf'
include { SUMMARY_SAMAP } from './modules/summary_samap.nf'
include { CONNECTED_DE } from './modules/connected_de.nf'
include { ADDITIONAL_ANALYSIS } from './modules/additional_analysis.nf'
include { validateParameters; paramsHelp; samplesheetToList } from 'plugin/nf-schema'

workflow {
    // Generate run ID unless one is provided
    run_id = params.run_id ?: "${new Date().format('yyyyMMdd_HHmmss')}"
    run_id_ch = Channel.value(run_id)

    // Stage static input files
    sample_sheet    = Channel.fromPath(params.sample_sheet)

    // Validation of necessary files
    if (!new File(params.sample_sheet).exists()) {
        error "Missing required file: sample sheet '${params.sample_sheet}'"
    }
    
    // Reformat Sample_Sheet to remove necessity of Sample_Sheet for downstream processes
    sample_sheet
        .map { file -> 
            def list = samplesheetToList(file.toString(), "./nf-samap/assets/schema_input.json")
            return list
        }
        .flatten()
        .collate(3)
        .set { ch_samples }

    // Grab all SO paths to extract relevant info
    SO = ch_samples
    .map { tuple ->
        def (meta, SO, fasta) = tuple
        return [meta, SO]
    }

    //PREPROCESS_SEURAT_OBJECT module here
    PREPROCESS_SEURAT_OBJECT(
        run_id_ch,
        SO
    )

    anndata_parts = PREPROCESS_SEURAT_OBJECT.out.seurat_data

    //PREPROCESS_ANNDATA_OBJECT module here
    PREPROCESS_ANNDATA_OBJECT(
        run_id_ch,
        anndata_parts
    )
    anndata = PREPROCESS_ANNDATA_OBJECT.out.anndata

 
     // Generate unique unordered sample pairs
    pairs_channel = ch_samples
        .combine(ch_samples)
        .filter { a,b,c,d,e,f -> a.id < d.id }  


    // Run BLAST or load precomputed map files 
   if (params.maps_dir) {
        // Use user-supplied BLAST maps
        maps_dir = Channel.fromPath(params.maps_dir)
    } else {
        // Run BLAST and extract parent maps directory
        RUN_BLAST_PAIR(
            run_id_ch,
            pairs_channel.map{[it[0], it[3], it[2], it[5]]}
        )
        // Set path to maps from BLAST results
    maps_dir = RUN_BLAST_PAIR.out.maps
    }

    // Grab all id values, to be used in LOAD_SAMS to reference the appropriate SAM object
    id = anndata
    .map { tuple ->
        def (id, h5ad) = tuple
        return id
    }
    .collect()

    // Grab all h5ad paths, to be used in LOAD_SAMS to reference the appropriate SAM object
    h5ad = anndata
    .map { tuple ->
        def (id, h5ad) = tuple
        return h5ad
    }
    .collect()
    
    //Combine into a single channel obj
    condensedSampleSheet = id
        .map { ids -> [ ids, h5ad.getVal() ] }
       
    // Load SAM objects from the AnnData h5ad files
    LOAD_SAMS(
        run_id_ch,
        condensedSampleSheet
    )
    sams = LOAD_SAMS.out.sams
    
    // Extract the mappings paths from the ch_samples object, pass as an additional parameter!!!
    map_dict = ch_samples
    .map { tuple ->
        def (meta, h5ad, fasta) = tuple
        return meta.map_dict
    }
    .collect()   

    // Build the SAMap object from the SAM objects and the BLAST maps
    BUILD_SAMAP(
        run_id_ch,
        condensedSampleSheet,
        maps_dir,
        sams,
        map_dict
    )
    samap = BUILD_SAMAP.out.samap

    // Run SAMap on the SAMAP object to generate mapping results
    RUN_SAMAP(
        run_id_ch,
        samap
    )
    samap_results = RUN_SAMAP.out.results

    // Building channel obj for visualization module
    anno = ch_samples
    .map { tuple ->
        def (meta, h5ad, fasta) = tuple
        return meta.annotation
    }
    .collect()

    annotations = id
        .map { ids -> [ ids, anno.getVal()] }

    // Visualize the SAMap results
     VISUALIZE_SAMAP(
        run_id_ch,
        samap_results,
        annotations
    )

    // Necessary Context
    id_anno = ch_samples
        .map { meta, h5ad, fasta -> [meta.id, meta.annotation] }
    id_anno.view()

    //Make id + Annotation pairs for pairwise post-analysis
    idCompare = id_anno.combine(id_anno)
        .filter { a_id, a_anno, b_id, b_anno -> a_id < b_id }
        .map { a_id, a_anno, b_id, b_anno ->
            [a_id, b_id, a_anno, b_anno]
    }
    idCompare.view()

    SUMMARY_SAMAP(
        run_id_ch,
        samap_results,
        idCompare,
        id_anno
    )
    genepairs = SUMMARY_SAMAP.out.genepairs
    cleaned = SUMMARY_SAMAP.out.samap_cleaned.map { id1, id2, pkl -> pkl }
    pms = SUMMARY_SAMAP.out.pms.map { id1, id2, pms -> pms }

 
    

    CONNECTED_DE(
        run_id_ch,
        cleaned,
        pms,
        idCompare
    )
    GroupingAnalysis = CONNECTED_DE.out.GroupingAnalysis
    //Grouping_Analysis.view()
    analysis = CONNECTED_DE.out.analysis
    //analysis.view()
    all_de_results = CONNECTED_DE.out.all_de_results
    //all_de_results.view()


    // Since genepairs, pms come from a different module, how can I make sure that the right order of
    // pms, genepairs, GroupingAnalysis, analysis, and all_de_results are passed into the next module correctly?
    combined = CONNECTED_DE.out.GroupingAnalysis
        .join(CONNECTED_DE.out.analysis,        by: [0,1])
        .join(CONNECTED_DE.out.all_de_results,  by: [0,1])
        .join(SUMMARY_SAMAP.out.genepairs,      by: [0,1])
        .join(SUMMARY_SAMAP.out.pms,            by: [0,1])
        .join(idCompare,                        by: [0,1])

    combined.view()


    ADDITIONAL_ANALYSIS(
        run_id_ch,
        combined
    )



    //CONSOLIDATION MODULE, make this contingent on >2 input species, otherwise skip

/*     NONPAIRWISE_ANALYSIS(
        id_anno
    ) */

} 
